# Generated by Django 6.0.3 on 2026-03-18 19:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('fathers_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('ADT', models.CharField(blank=True, max_length=20, validators=[django.core.validators.MinLengthValidator(5)])),
                ('AFM', models.CharField(blank=True, max_length=20, validators=[django.core.validators.MinLengthValidator(9)])),
                ('AMKA', models.CharField(blank=True, max_length=20, validators=[django.core.validators.MinLengthValidator(11)])),
                ('mitroo_type', models.CharField(choices=[('A', 'Type A'), ('B', 'Type B')], max_length=1)),
                ('mitroo_number', models.CharField(blank=True, max_length=20, validators=[django.core.validators.MinLengthValidator(5)])),
                ('date_of_registration', models.DateField(auto_now_add=True)),
                ('date_of_deregistration', models.DateField(auto_now_add=True)),
                ('driver_A', models.BooleanField(default=False)),
                ('driver_B', models.BooleanField(default=False)),
                ('driver_C', models.BooleanField(default=False)),
                ('driver_D', models.BooleanField(default=False)),
                ('lifter', models.BooleanField(default=False)),
                ('omadiko_from', models.DateField(blank=True, null=True)),
                ('omadiko_to', models.DateField(blank=True, null=True)),
                ('bank_account_number', models.CharField(max_length=30)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number1', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number2', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('pending_issues', models.TextField(blank=True, null=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.banks')),
            ],
        ),
    ]
