# Generated by Django 6.0.3 on 2026-03-19 12:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
            options={
                'verbose_name': 'Τράπεζα',
                'verbose_name_plural': 'Τράπεζες',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('AFM', models.CharField(max_length=20, unique=True)),
                ('DOY', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('services', models.TextField(blank=True, null=True)),
                ('ekremotes_ofiles', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('active_date', models.DateField(auto_now_add=True)),
                ('inactive_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Εταιρεία',
                'verbose_name_plural': 'Εταιρείες',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='nationalities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
            options={
                'verbose_name': 'Ιθαγένεια',
                'verbose_name_plural': 'Ιθαγένειες',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
            options={
                'verbose_name': 'Ιδιότητα Εξαρτώμενου',
            },
        ),
        migrations.CreateModel(
            name='Companies_contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('idiotita', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.companies')),
            ],
            options={
                'verbose_name': 'Επαφή Εταιρείας',
                'verbose_name_plural': 'Επαφές Εταιρειών',
            },
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_type', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_issue', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.companies')),
            ],
            options={
                'verbose_name': 'Τιμολόγιο',
                'verbose_name_plural': 'Τιμολόγια',
                'ordering': ['-date_of_issue'],
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Όνομα')),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Επίθετο')),
                ('fathers_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Πατρώνυμο')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Άνδρας'), ('F', 'Γυναίκα')], max_length=1, null=True, verbose_name='Φύλο')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Ημ. Γέννησης')),
                ('ADT', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ΑΔΤ')),
                ('AFM', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ΑΦΜ')),
                ('AMKA', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ΑΜΚΑ')),
                ('AMA', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ΑΜΑ')),
                ('mitroo_type', models.CharField(blank=True, choices=[('A', 'Τύπος Α'), ('B', 'Τύπος Β')], max_length=1, null=True, verbose_name='Τύπος Μητρώου')),
                ('mitroo_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Αριθμός Μητρώου')),
                ('date_of_registration', models.DateField(blank=True, null=True, verbose_name='Ημ. Εγγραφής')),
                ('date_of_deregistration', models.DateField(blank=True, null=True, verbose_name='Ημ. Λήξης')),
                ('driver_A', models.BooleanField(default=False, verbose_name='Δίπλωμα Α')),
                ('driver_B', models.BooleanField(default=False, verbose_name='Δίπλωμα Β')),
                ('driver_C', models.BooleanField(default=False, verbose_name='Δίπλωμα Γ')),
                ('driver_D', models.BooleanField(default=False, verbose_name='Δίπλωμα Δ')),
                ('lifter', models.BooleanField(default=False, verbose_name='Χειριστής Ανυψωτικού')),
                ('omadiko', models.BooleanField(default=False, verbose_name='Ομαδικό')),
                ('omadiko_from', models.DateField(blank=True, null=True, verbose_name='Ομαδικό Από')),
                ('omadiko_to', models.DateField(blank=True, null=True, verbose_name='Ομαδικό Έως')),
                ('omadiko_exartomena', models.BooleanField(default=False, verbose_name='Ομαδικό Εξαρτώμενων')),
                ('bank_account_number', models.CharField(blank=True, max_length=34, null=True, unique=True, verbose_name='IBAN')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Διεύθυνση')),
                ('tk', models.CharField(blank=True, max_length=10, null=True, verbose_name='ΤΚ')),
                ('phone_number1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Τηλ. 1')),
                ('phone_number2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Τηλ. 2')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Παρατηρήσεις')),
                ('pending_issues', models.TextField(blank=True, null=True, verbose_name='Εκκρεμότητες')),
                ('active', models.BooleanField(default=True)),
                ('active_date', models.DateField(auto_now_add=True)),
                ('inactive_date', models.DateField(blank=True, null=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.banks', verbose_name='Τράπεζα')),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.nationalities', verbose_name='Ιθαγένεια')),
            ],
            options={
                'verbose_name': 'Μέλος',
                'verbose_name_plural': 'Μέλη',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Exartomena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exartomena', to='core.members')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exartomena', to='core.properties')),
            ],
            options={
                'verbose_name': 'Εξαρτώμενο',
                'verbose_name_plural': 'Εξαρτώμενα',
            },
        ),
        migrations.CreateModel(
            name='companies_members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.companies')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='core.members')),
            ],
            options={
                'verbose_name': 'Απασχόληση',
                'unique_together': {('company', 'member')},
            },
        ),
    ]
