# Generated by Django 6.0.3 on 2026-03-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='ADT',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='ΑΔΤ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='members',
            name='AFM',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='ΑΦΜ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='members',
            name='AMA',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='ΑΜΑ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='members',
            name='AMKA',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='ΑΜΚΑ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='members',
            name='bank_account_number',
            field=models.CharField(max_length=34, null=True, unique=True, verbose_name='IBAN'),
        ),
    ]
