# Generated by Django 6.0.3 on 2026-03-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_invoices_scan_file_companies_members_status_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_number', models.PositiveIntegerField(verbose_name='Αριθμός Πρωτοκόλλου')),
                ('year', models.PositiveIntegerField(verbose_name='Έτος')),
                ('date', models.DateField(verbose_name='Ημερομηνία')),
                ('subject', models.CharField(max_length=500, verbose_name='Θέμα')),
                ('file', models.FileField(blank=True, null=True, upload_to='protocols/%Y/', verbose_name='Αρχείο')),
                ('receiver_last_name', models.CharField(blank=True, max_length=100, verbose_name='Επώνυμο Παραλήπτη')),
                ('receiver_first_name', models.CharField(blank=True, max_length=100, verbose_name='Όνομα Παραλήπτη')),
                ('receiver_organization', models.CharField(blank=True, max_length=200, verbose_name='Οργανισμός / Υπηρεσία')),
                ('receiver_department', models.CharField(blank=True, max_length=200, verbose_name='Τμήμα')),
                ('receiver_address', models.CharField(blank=True, max_length=255, verbose_name='Διεύθυνση')),
                ('receiver_tk', models.CharField(blank=True, max_length=10, verbose_name='Τ.Κ.')),
                ('receiver_phone', models.CharField(blank=True, max_length=20, verbose_name='Τηλέφωνο')),
                ('receiver_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Πρωτόκολλο',
                'verbose_name_plural': 'Πρωτόκολλα',
                'ordering': ['-year', '-protocol_number'],
                'unique_together': {('protocol_number', 'year')},
            },
        ),
    ]
