# Generated by Django 6.0.3 on 2026-03-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='sender_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Διεύθυνση Αποστολέα'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='sender_department',
            field=models.CharField(blank=True, max_length=200, verbose_name='Τμήμα Αποστολέα'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='sender_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Αποστολέα'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='sender_first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Όνομα Αποστολέα'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='sender_last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Επώνυμο Αποστολέα'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='sender_organization',
            field=models.CharField(blank=True, max_length=200, verbose_name='Οργανισμός Αποστολέα'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='sender_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Τηλέφωνο Αποστολέα'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='sender_tk',
            field=models.CharField(blank=True, max_length=10, verbose_name='Τ.Κ. Αποστολέα'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='receiver_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Διεύθυνση Παραλήπτη'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='receiver_department',
            field=models.CharField(blank=True, max_length=200, verbose_name='Τμήμα Παραλήπτη'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='receiver_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Παραλήπτη'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='receiver_organization',
            field=models.CharField(blank=True, max_length=200, verbose_name='Οργανισμός Παραλήπτη'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='receiver_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Τηλέφωνο Παραλήπτη'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='receiver_tk',
            field=models.CharField(blank=True, max_length=10, verbose_name='Τ.Κ. Παραλήπτη'),
        ),
    ]
