# Generated by Django 6.0.3 on 2026-03-24 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_protocol_sender_address_protocol_sender_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='members/%Y/', verbose_name='Αρχείο')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Περιγραφή')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.members')),
            ],
            options={
                'verbose_name': 'Αρχείο Μέλους',
                'verbose_name_plural': 'Αρχεία Μέλους',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
