# Generated by Django 6.0.3 on 2026-03-24 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_memberfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Επωνυμία')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Διεύθυνση')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Τηλέφωνο')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('contact_person', models.CharField(blank=True, max_length=150, verbose_name='Υπεύθυνος Επικοινωνίας')),
                ('notes', models.TextField(blank=True, verbose_name='Παρατηρήσεις')),
            ],
            options={
                'verbose_name': 'Ασφαλιστική Εταιρεία',
                'verbose_name_plural': 'Ασφαλιστικές Εταιρείες',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=100, verbose_name='Αριθμός Συμβολαίου')),
                ('coverage_type', models.CharField(blank=True, max_length=200, verbose_name='Τύπος Κάλυψης')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ποσό Ασφαλίστρου')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Ημ. Έναρξης')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ημ. Λήξης')),
                ('active', models.BooleanField(default=True, verbose_name='Ενεργό')),
                ('notes', models.TextField(blank=True, verbose_name='Παρατηρήσεις')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='core.insurancecompany', verbose_name='Ασφαλιστική Εταιρεία')),
            ],
            options={
                'verbose_name': 'Ασφαλιστικό Συμβόλαιο',
                'verbose_name_plural': 'Ασφαλιστικά Συμβόλαια',
                'ordering': ['-start_date'],
                'unique_together': {('company', 'contract_number')},
            },
        ),
        migrations.CreateModel(
            name='MemberInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('includes_dependents', models.BooleanField(default=False, verbose_name='Περιλαμβάνει Εξαρτώμενα')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.insurancecontract', verbose_name='Συμβόλαιο')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_contracts', to='core.members', verbose_name='Μέλος')),
            ],
            options={
                'verbose_name': 'Ασφάλιση Μέλους',
                'verbose_name_plural': 'Ασφαλίσεις Μελών',
                'unique_together': {('member', 'contract')},
            },
        ),
    ]
