# Generated by Django 6.0.3 on 2026-03-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_members_member_registry_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='member_registry_number',
        ),
        migrations.AddField(
            model_name='companies_members',
            name='member_registry_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Αριθμός Βιβλίου Μητρώου Μελών'),
        ),
    ]
