# Generated by Django 6.0.3 on 2026-03-25 19:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_move_member_registry_number_back_to_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banks',
            options={'ordering': ['name'], 'verbose_name': 'Ξ¤Ο\x81Ξ¬Ο€ΞµΞ¶Ξ±', 'verbose_name_plural': 'Ξ¤Ο\x81Ξ¬Ο€ΞµΞ¶ΞµΟ‚'},
        ),
        migrations.AlterModelOptions(
            name='companies',
            options={'ordering': ['name'], 'verbose_name': 'Ξ•Ο„Ξ±ΞΉΟ\x81ΞµΞ―Ξ±', 'verbose_name_plural': 'Ξ•Ο„Ξ±ΞΉΟ\x81ΞµΞ―ΞµΟ‚'},
        ),
        migrations.AlterModelOptions(
            name='companies_contacts',
            options={'verbose_name': 'Ξ•Ο€Ξ±Ο†Ξ® Ξ•Ο„Ξ±ΞΉΟ\x81ΞµΞ―Ξ±Ο‚', 'verbose_name_plural': 'Ξ•Ο€Ξ±Ο†Ξ\xadΟ‚ Ξ•Ο„Ξ±ΞΉΟ\x81ΞµΞΉΟ\x8eΞ½'},
        ),
        migrations.AlterModelOptions(
            name='companies_members',
            options={'verbose_name': 'Ξ‘Ο€Ξ±ΟƒΟ‡Ο\x8cΞ»Ξ·ΟƒΞ·'},
        ),
        migrations.AlterModelOptions(
            name='companypayment',
            options={'ordering': ['-payment_date', '-id'], 'verbose_name': 'Ξ\xa0Ξ»Ξ·Ο\x81Ο‰ΞΌΞ® ΞµΟ„Ξ±ΞΉΟ\x81Ξ―Ξ±Ο‚', 'verbose_name_plural': 'Ξ\xa0Ξ»Ξ·Ο\x81Ο‰ΞΌΞ\xadΟ‚ ΞµΟ„Ξ±ΞΉΟ\x81ΞΉΟ\x8eΞ½'},
        ),
        migrations.AlterModelOptions(
            name='exartomena',
            options={'verbose_name': 'Ξ•ΞΎΞ±Ο\x81Ο„Ο\x8eΞΌΞµΞ½ΞΏ', 'verbose_name_plural': 'Ξ•ΞΎΞ±Ο\x81Ο„Ο\x8eΞΌΞµΞ½Ξ±'},
        ),
        migrations.AlterModelOptions(
            name='insurancecompany',
            options={'ordering': ['name'], 'verbose_name': 'Ξ‘ΟƒΟ†Ξ±Ξ»ΞΉΟƒΟ„ΞΉΞΊΞ® Ξ•Ο„Ξ±ΞΉΟ\x81ΞµΞ―Ξ±', 'verbose_name_plural': 'Ξ‘ΟƒΟ†Ξ±Ξ»ΞΉΟƒΟ„ΞΉΞΊΞ\xadΟ‚ Ξ•Ο„Ξ±ΞΉΟ\x81ΞµΞ―ΞµΟ‚'},
        ),
        migrations.AlterModelOptions(
            name='insurancecontract',
            options={'ordering': ['-start_date'], 'verbose_name': 'Ξ‘ΟƒΟ†Ξ±Ξ»ΞΉΟƒΟ„ΞΉΞΊΟ\x8c Ξ£Ο…ΞΌΞ²Ο\x8cΞ»Ξ±ΞΉΞΏ', 'verbose_name_plural': 'Ξ‘ΟƒΟ†Ξ±Ξ»ΞΉΟƒΟ„ΞΉΞΊΞ¬ Ξ£Ο…ΞΌΞ²Ο\x8cΞ»Ξ±ΞΉΞ±'},
        ),
        migrations.AlterModelOptions(
            name='invoices',
            options={'ordering': ['-date_of_issue'], 'verbose_name': 'Ξ¤ΞΉΞΌΞΏΞ»Ο\x8cΞ³ΞΉΞΏ', 'verbose_name_plural': 'Ξ¤ΞΉΞΌΞΏΞ»Ο\x8cΞ³ΞΉΞ±'},
        ),
        migrations.AlterModelOptions(
            name='memberfile',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Ξ‘Ο\x81Ο‡ΞµΞ―ΞΏ Ξ\x9cΞ\xadΞ»ΞΏΟ…Ο‚', 'verbose_name_plural': 'Ξ‘Ο\x81Ο‡ΞµΞ―Ξ± Ξ\x9cΞ\xadΞ»ΞΏΟ…Ο‚'},
        ),
        migrations.AlterModelOptions(
            name='memberinsurance',
            options={'verbose_name': 'Ξ‘ΟƒΟ†Ξ¬Ξ»ΞΉΟƒΞ· Ξ\x9cΞ\xadΞ»ΞΏΟ…Ο‚', 'verbose_name_plural': 'Ξ‘ΟƒΟ†Ξ±Ξ»Ξ―ΟƒΞµΞΉΟ‚ Ξ\x9cΞµΞ»Ο\x8eΞ½'},
        ),
        migrations.AlterModelOptions(
            name='members',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Ξ\x9cΞ\xadΞ»ΞΏΟ‚', 'verbose_name_plural': 'Ξ\x9cΞ\xadΞ»Ξ·'},
        ),
        migrations.AlterModelOptions(
            name='nationalities',
            options={'ordering': ['name'], 'verbose_name': 'Ξ™ΞΈΞ±Ξ³Ξ\xadΞ½ΞµΞΉΞ±', 'verbose_name_plural': 'Ξ™ΞΈΞ±Ξ³Ξ\xadΞ½ΞµΞΉΞµΟ‚'},
        ),
        migrations.AlterModelOptions(
            name='properties',
            options={'verbose_name': 'Ξ™Ξ΄ΞΉΟ\x8cΟ„Ξ·Ο„Ξ± Ξ•ΞΎΞ±Ο\x81Ο„Ο\x8eΞΌΞµΞ½ΞΏΟ…'},
        ),
        migrations.AlterModelOptions(
            name='protocol',
            options={'ordering': ['-year', '-protocol_number'], 'verbose_name': 'Ξ\xa0Ο\x81Ο‰Ο„Ο\x8cΞΊΞΏΞ»Ξ»ΞΏ', 'verbose_name_plural': 'Ξ\xa0Ο\x81Ο‰Ο„Ο\x8cΞΊΞΏΞ»Ξ»Ξ±'},
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ξ”ΞΉΞµΟ\x8dΞΈΟ…Ξ½ΟƒΞ·'),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='contact_person',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ξ¥Ο€ΞµΟ\x8dΞΈΟ…Ξ½ΞΏΟ‚ Ξ•Ο€ΞΉΞΊΞΏΞΉΞ½Ο‰Ξ½Ξ―Ξ±Ο‚'),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Ξ•Ο€Ο‰Ξ½Ο…ΞΌΞ―Ξ±'),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Ξ\xa0Ξ±Ο\x81Ξ±Ο„Ξ·Ο\x81Ξ®ΟƒΞµΞΉΟ‚'),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Ξ¤Ξ·Ξ»Ξ\xadΟ†Ο‰Ξ½ΞΏ'),
        ),
        migrations.AlterField(
            model_name='insurancecontract',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ξ•Ξ½ΞµΟ\x81Ξ³Ο\x8c'),
        ),
        migrations.AlterField(
            model_name='insurancecontract',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ξ\xa0ΞΏΟƒΟ\x8c Ξ‘ΟƒΟ†Ξ±Ξ»Ξ―ΟƒΟ„Ο\x81ΞΏΟ…'),
        ),
        migrations.AlterField(
            model_name='insurancecontract',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='core.insurancecompany', verbose_name='Ξ‘ΟƒΟ†Ξ±Ξ»ΞΉΟƒΟ„ΞΉΞΊΞ® Ξ•Ο„Ξ±ΞΉΟ\x81ΞµΞ―Ξ±'),
        ),
        migrations.AlterField(
            model_name='insurancecontract',
            name='contract_number',
            field=models.CharField(max_length=100, verbose_name='Ξ‘Ο\x81ΞΉΞΈΞΌΟ\x8cΟ‚ Ξ£Ο…ΞΌΞ²ΞΏΞ»Ξ±Ξ―ΞΏΟ…'),
        ),
        migrations.AlterField(
            model_name='insurancecontract',
            name='coverage_type',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ξ¤Ο\x8dΟ€ΞΏΟ‚ Ξ\x9aΞ¬Ξ»Ο…Ο\x88Ξ·Ο‚'),
        ),
        migrations.AlterField(
            model_name='insurancecontract',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ξ—ΞΌ. Ξ›Ξ®ΞΎΞ·Ο‚'),
        ),
        migrations.AlterField(
            model_name='insurancecontract',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Ξ\xa0Ξ±Ο\x81Ξ±Ο„Ξ·Ο\x81Ξ®ΟƒΞµΞΉΟ‚'),
        ),
        migrations.AlterField(
            model_name='insurancecontract',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ξ—ΞΌ. Ξ\x88Ξ½Ξ±Ο\x81ΞΎΞ·Ο‚'),
        ),
        migrations.AlterField(
            model_name='memberfile',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ξ\xa0ΞµΟ\x81ΞΉΞ³Ο\x81Ξ±Ο†Ξ®'),
        ),
        migrations.AlterField(
            model_name='memberfile',
            name='file',
            field=models.FileField(upload_to='members/%Y/', verbose_name='Ξ‘Ο\x81Ο‡ΞµΞ―ΞΏ'),
        ),
        migrations.AlterField(
            model_name='memberinsurance',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.insurancecontract', verbose_name='Ξ£Ο…ΞΌΞ²Ο\x8cΞ»Ξ±ΞΉΞΏ'),
        ),
        migrations.AlterField(
            model_name='memberinsurance',
            name='includes_dependents',
            field=models.BooleanField(default=False, verbose_name='Ξ\xa0ΞµΟ\x81ΞΉΞ»Ξ±ΞΌΞ²Ξ¬Ξ½ΞµΞΉ Ξ•ΞΎΞ±Ο\x81Ο„Ο\x8eΞΌΞµΞ½Ξ±'),
        ),
        migrations.AlterField(
            model_name='memberinsurance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_contracts', to='core.members', verbose_name='Ξ\x9cΞ\xadΞ»ΞΏΟ‚'),
        ),
        migrations.AlterField(
            model_name='members',
            name='ADT',
            field=models.CharField(max_length=20, unique=True, verbose_name='Ξ‘Ξ”Ξ¤'),
        ),
        migrations.AlterField(
            model_name='members',
            name='AFM',
            field=models.CharField(max_length=20, unique=True, verbose_name='Ξ‘Ξ¦Ξ\x9c'),
        ),
        migrations.AlterField(
            model_name='members',
            name='AMA',
            field=models.CharField(max_length=20, unique=True, verbose_name='Ξ‘Ξ\x9cΞ‘'),
        ),
        migrations.AlterField(
            model_name='members',
            name='AMKA',
            field=models.CharField(max_length=20, unique=True, verbose_name='Ξ‘Ξ\x9cΞ\x9aΞ‘'),
        ),
        migrations.AlterField(
            model_name='members',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ξ”ΞΉΞµΟ\x8dΞΈΟ…Ξ½ΟƒΞ·'),
        ),
        migrations.AlterField(
            model_name='members',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.banks', verbose_name='Ξ¤Ο\x81Ξ¬Ο€ΞµΞ¶Ξ±'),
        ),
        migrations.AlterField(
            model_name='members',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Ξ—ΞΌ. Ξ“Ξ\xadΞ½Ξ½Ξ·ΟƒΞ·Ο‚'),
        ),
        migrations.AlterField(
            model_name='members',
            name='date_of_deregistration',
            field=models.DateField(blank=True, null=True, verbose_name='Ξ—ΞΌ. Ξ›Ξ®ΞΎΞ·Ο‚'),
        ),
        migrations.AlterField(
            model_name='members',
            name='date_of_registration',
            field=models.DateField(blank=True, null=True, verbose_name='Ξ—ΞΌ. Ξ•Ξ³Ξ³Ο\x81Ξ±Ο†Ξ®Ο‚'),
        ),
        migrations.AlterField(
            model_name='members',
            name='driver_A',
            field=models.BooleanField(default=False, verbose_name='Ξ”Ξ―Ο€Ξ»Ο‰ΞΌΞ± Ξ‘'),
        ),
        migrations.AlterField(
            model_name='members',
            name='driver_B',
            field=models.BooleanField(default=False, verbose_name='Ξ”Ξ―Ο€Ξ»Ο‰ΞΌΞ± Ξ’'),
        ),
        migrations.AlterField(
            model_name='members',
            name='driver_C',
            field=models.BooleanField(default=False, verbose_name='Ξ”Ξ―Ο€Ξ»Ο‰ΞΌΞ± Ξ“'),
        ),
        migrations.AlterField(
            model_name='members',
            name='driver_D',
            field=models.BooleanField(default=False, verbose_name='Ξ”Ξ―Ο€Ξ»Ο‰ΞΌΞ± Ξ”'),
        ),
        migrations.AlterField(
            model_name='members',
            name='fathers_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Ξ\xa0Ξ±Ο„Ο\x81Ο\x8eΞ½Ο…ΞΌΞΏ'),
        ),
        migrations.AlterField(
            model_name='members',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Ξ\x8cΞ½ΞΏΞΌΞ±'),
        ),
        migrations.AlterField(
            model_name='members',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Ξ†Ξ½Ξ΄Ο\x81Ξ±Ο‚'), ('F', 'Ξ“Ο…Ξ½Ξ±Ξ―ΞΊΞ±')], max_length=1, null=True, verbose_name='Ξ¦Ο\x8dΞ»ΞΏ'),
        ),
        migrations.AlterField(
            model_name='members',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Ξ•Ο€Ξ―ΞΈΞµΟ„ΞΏ'),
        ),
        migrations.AlterField(
            model_name='members',
            name='lifter',
            field=models.BooleanField(default=False, verbose_name='Ξ§ΞµΞΉΟ\x81ΞΉΟƒΟ„Ξ®Ο‚ Ξ‘Ξ½Ο…Ο\x88Ο‰Ο„ΞΉΞΊΞΏΟ\x8d'),
        ),
        migrations.AlterField(
            model_name='members',
            name='mitroo_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ξ‘Ο\x81ΞΉΞΈΞΌΟ\x8cΟ‚ Ξ\x9cΞ·Ο„Ο\x81Ο\x8eΞΏΟ…'),
        ),
        migrations.AlterField(
            model_name='members',
            name='mitroo_type',
            field=models.CharField(blank=True, choices=[('A', 'Ξ¤Ο\x8dΟ€ΞΏΟ‚ Ξ‘'), ('B', 'Ξ¤Ο\x8dΟ€ΞΏΟ‚ Ξ’')], max_length=1, null=True, verbose_name='Ξ¤Ο\x8dΟ€ΞΏΟ‚ Ξ\x9cΞ·Ο„Ο\x81Ο\x8eΞΏΟ…'),
        ),
        migrations.AlterField(
            model_name='members',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.nationalities', verbose_name='Ξ™ΞΈΞ±Ξ³Ξ\xadΞ½ΞµΞΉΞ±'),
        ),
        migrations.AlterField(
            model_name='members',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Ξ\xa0Ξ±Ο\x81Ξ±Ο„Ξ·Ο\x81Ξ®ΟƒΞµΞΉΟ‚'),
        ),
        migrations.AlterField(
            model_name='members',
            name='omadiko',
            field=models.BooleanField(default=False, verbose_name='Ξ\x9fΞΌΞ±Ξ΄ΞΉΞΊΟ\x8c'),
        ),
        migrations.AlterField(
            model_name='members',
            name='omadiko_exartomena',
            field=models.BooleanField(default=False, verbose_name='Ξ\x9fΞΌΞ±Ξ΄ΞΉΞΊΟ\x8c Ξ•ΞΎΞ±Ο\x81Ο„Ο\x8eΞΌΞµΞ½Ο‰Ξ½'),
        ),
        migrations.AlterField(
            model_name='members',
            name='omadiko_from',
            field=models.DateField(blank=True, null=True, verbose_name='Ξ\x9fΞΌΞ±Ξ΄ΞΉΞΊΟ\x8c Ξ‘Ο€Ο\x8c'),
        ),
        migrations.AlterField(
            model_name='members',
            name='omadiko_to',
            field=models.DateField(blank=True, null=True, verbose_name='Ξ\x9fΞΌΞ±Ξ΄ΞΉΞΊΟ\x8c Ξ\x88Ο‰Ο‚'),
        ),
        migrations.AlterField(
            model_name='members',
            name='pending_issues',
            field=models.TextField(blank=True, null=True, verbose_name='Ξ•ΞΊΞΊΟ\x81ΞµΞΌΟ\x8cΟ„Ξ·Ο„ΞµΟ‚'),
        ),
        migrations.AlterField(
            model_name='members',
            name='phone_number1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ξ¤Ξ·Ξ». 1'),
        ),
        migrations.AlterField(
            model_name='members',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ξ¤Ξ·Ξ». 2'),
        ),
        migrations.AlterField(
            model_name='members',
            name='tk',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Ξ¤Ξ\x9a'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='date',
            field=models.DateField(verbose_name='Ξ—ΞΌΞµΟ\x81ΞΏΞΌΞ·Ξ½Ξ―Ξ±'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='protocols/%Y/', verbose_name='Ξ‘Ο\x81Ο‡ΞµΞ―ΞΏ'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='protocol_number',
            field=models.PositiveIntegerField(verbose_name='Ξ‘Ο\x81ΞΉΞΈΞΌΟ\x8cΟ‚ Ξ\xa0Ο\x81Ο‰Ο„ΞΏΞΊΟ\x8cΞ»Ξ»ΞΏΟ…'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='receiver_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ξ”ΞΉΞµΟ\x8dΞΈΟ…Ξ½ΟƒΞ· Ξ\xa0Ξ±Ο\x81Ξ±Ξ»Ξ®Ο€Ο„Ξ·'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='receiver_department',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ξ¤ΞΌΞ®ΞΌΞ± Ξ\xa0Ξ±Ο\x81Ξ±Ξ»Ξ®Ο€Ο„Ξ·'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='receiver_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Ξ\xa0Ξ±Ο\x81Ξ±Ξ»Ξ®Ο€Ο„Ξ·'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='receiver_first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ξ\x8cΞ½ΞΏΞΌΞ± Ξ\xa0Ξ±Ο\x81Ξ±Ξ»Ξ®Ο€Ο„Ξ·'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='receiver_last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ξ•Ο€Ο\x8eΞ½Ο…ΞΌΞΏ Ξ\xa0Ξ±Ο\x81Ξ±Ξ»Ξ®Ο€Ο„Ξ·'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='receiver_organization',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ξ\x9fΟ\x81Ξ³Ξ±Ξ½ΞΉΟƒΞΌΟ\x8cΟ‚ Ξ\xa0Ξ±Ο\x81Ξ±Ξ»Ξ®Ο€Ο„Ξ·'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='receiver_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Ξ¤Ξ·Ξ»Ξ\xadΟ†Ο‰Ξ½ΞΏ Ξ\xa0Ξ±Ο\x81Ξ±Ξ»Ξ®Ο€Ο„Ξ·'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='receiver_tk',
            field=models.CharField(blank=True, max_length=10, verbose_name='Ξ¤.Ξ\x9a. Ξ\xa0Ξ±Ο\x81Ξ±Ξ»Ξ®Ο€Ο„Ξ·'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='sender_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ξ”ΞΉΞµΟ\x8dΞΈΟ…Ξ½ΟƒΞ· Ξ‘Ο€ΞΏΟƒΟ„ΞΏΞ»Ξ\xadΞ±'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='sender_department',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ξ¤ΞΌΞ®ΞΌΞ± Ξ‘Ο€ΞΏΟƒΟ„ΞΏΞ»Ξ\xadΞ±'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='sender_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Ξ‘Ο€ΞΏΟƒΟ„ΞΏΞ»Ξ\xadΞ±'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='sender_first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ξ\x8cΞ½ΞΏΞΌΞ± Ξ‘Ο€ΞΏΟƒΟ„ΞΏΞ»Ξ\xadΞ±'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='sender_last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ξ•Ο€Ο\x8eΞ½Ο…ΞΌΞΏ Ξ‘Ο€ΞΏΟƒΟ„ΞΏΞ»Ξ\xadΞ±'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='sender_organization',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ξ\x9fΟ\x81Ξ³Ξ±Ξ½ΞΉΟƒΞΌΟ\x8cΟ‚ Ξ‘Ο€ΞΏΟƒΟ„ΞΏΞ»Ξ\xadΞ±'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='sender_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Ξ¤Ξ·Ξ»Ξ\xadΟ†Ο‰Ξ½ΞΏ Ξ‘Ο€ΞΏΟƒΟ„ΞΏΞ»Ξ\xadΞ±'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='sender_tk',
            field=models.CharField(blank=True, max_length=10, verbose_name='Ξ¤.Ξ\x9a. Ξ‘Ο€ΞΏΟƒΟ„ΞΏΞ»Ξ\xadΞ±'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='subject',
            field=models.CharField(max_length=500, verbose_name='Ξ\x98Ξ\xadΞΌΞ±'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Ξ\x88Ο„ΞΏΟ‚'),
        ),
    ]
