# Generated by Django 6.0.3 on 2026-03-25 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_banks_options_alter_companies_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Άνδρας'), ('F', 'Γυναίκα')], max_length=1, null=True, verbose_name='Φύλο'),
        ),
        migrations.AlterField(
            model_name='members',
            name='mitroo_type',
            field=models.CharField(blank=True, choices=[('A', 'Τύπος Α'), ('B', 'Τύπος Β')], max_length=1, null=True, verbose_name='Τύπος Μητρώου'),
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.invoices')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.companypayment')),
            ],
            options={
                'ordering': ['invoice__date_of_issue', 'invoice_id', 'payment__payment_date', 'payment_id'],
                'unique_together': {('payment', 'invoice')},
            },
        ),
    ]
