# Generated by Django 6.0.3 on 2026-04-05 11:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_backfill_payment_allocations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banks',
            options={'ordering': ['name'], 'verbose_name': 'Τράπεζα', 'verbose_name_plural': 'Τράπεζες'},
        ),
        migrations.AlterModelOptions(
            name='companies',
            options={'ordering': ['name'], 'verbose_name': 'Εταιρεία', 'verbose_name_plural': 'Εταιρείες'},
        ),
        migrations.AlterModelOptions(
            name='companies_contacts',
            options={'verbose_name': 'Επαφή Εταιρείας', 'verbose_name_plural': 'Επαφές Εταιρειών'},
        ),
        migrations.AlterModelOptions(
            name='companies_members',
            options={'verbose_name': 'Απασχόληση'},
        ),
        migrations.AlterModelOptions(
            name='companypayment',
            options={'ordering': ['-payment_date', '-id'], 'verbose_name': 'Πληρωμή εταιρίας', 'verbose_name_plural': 'Πληρωμές εταιριών'},
        ),
        migrations.AlterModelOptions(
            name='exartomena',
            options={'verbose_name': 'Εξαρτώμενο', 'verbose_name_plural': 'Εξαρτώμενα'},
        ),
        migrations.AlterModelOptions(
            name='insurancecompany',
            options={'ordering': ['name'], 'verbose_name': 'Ασφαλιστική Εταιρεία', 'verbose_name_plural': 'Ασφαλιστικές Εταιρείες'},
        ),
        migrations.AlterModelOptions(
            name='insurancecontract',
            options={'ordering': ['-start_date'], 'verbose_name': 'Ασφαλιστικό Συμβόλαιο', 'verbose_name_plural': 'Ασφαλιστικά Συμβόλαια'},
        ),
        migrations.AlterModelOptions(
            name='invoices',
            options={'ordering': ['-date_of_issue'], 'verbose_name': 'Τιμολόγιο', 'verbose_name_plural': 'Τιμολόγια'},
        ),
        migrations.AlterModelOptions(
            name='memberfile',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Αρχείο Μέλους', 'verbose_name_plural': 'Αρχεία Μέλους'},
        ),
        migrations.AlterModelOptions(
            name='memberinsurance',
            options={'verbose_name': 'Ασφάλιση Μέλους', 'verbose_name_plural': 'Ασφαλίσεις Μελών'},
        ),
        migrations.AlterModelOptions(
            name='members',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Μέλος', 'verbose_name_plural': 'Μέλη'},
        ),
        migrations.AlterModelOptions(
            name='nationalities',
            options={'ordering': ['name'], 'verbose_name': 'Ιθαγένεια', 'verbose_name_plural': 'Ιθαγένειες'},
        ),
        migrations.AlterModelOptions(
            name='properties',
            options={'verbose_name': 'Ιδιότητα Εξαρτώμενου'},
        ),
        migrations.AlterModelOptions(
            name='protocol',
            options={'ordering': ['-year', '-protocol_number'], 'verbose_name': 'Πρωτόκολλο', 'verbose_name_plural': 'Πρωτόκολλα'},
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Διεύθυνση'),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='contact_person',
            field=models.CharField(blank=True, max_length=150, verbose_name='Υπεύθυνος Επικοινωνίας'),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Επωνυμία'),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Παρατηρήσεις'),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Τηλέφωνο'),
        ),
        migrations.AlterField(
            model_name='insurancecontract',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ενεργό'),
        ),
        migrations.AlterField(
            model_name='insurancecontract',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ποσό Ασφαλίστρου'),
        ),
        migrations.AlterField(
            model_name='insurancecontract',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='core.insurancecompany', verbose_name='Ασφαλιστική Εταιρεία'),
        ),
        migrations.AlterField(
            model_name='insurancecontract',
            name='contract_number',
            field=models.CharField(max_length=100, verbose_name='Αριθμός Συμβολαίου'),
        ),
        migrations.AlterField(
            model_name='insurancecontract',
            name='coverage_type',
            field=models.CharField(blank=True, max_length=200, verbose_name='Τύπος Κάλυψης'),
        ),
        migrations.AlterField(
            model_name='insurancecontract',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ημ. Λήξης'),
        ),
        migrations.AlterField(
            model_name='insurancecontract',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Παρατηρήσεις'),
        ),
        migrations.AlterField(
            model_name='insurancecontract',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ημ. Έναρξης'),
        ),
        migrations.AlterField(
            model_name='memberfile',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Περιγραφή'),
        ),
        migrations.AlterField(
            model_name='memberfile',
            name='file',
            field=models.FileField(upload_to='members/%Y/', verbose_name='Αρχείο'),
        ),
        migrations.AlterField(
            model_name='memberinsurance',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.insurancecontract', verbose_name='Συμβόλαιο'),
        ),
        migrations.AlterField(
            model_name='memberinsurance',
            name='includes_dependents',
            field=models.BooleanField(default=False, verbose_name='Περιλαμβάνει Εξαρτώμενα'),
        ),
        migrations.AlterField(
            model_name='memberinsurance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_contracts', to='core.members', verbose_name='Μέλος'),
        ),
        migrations.AlterField(
            model_name='members',
            name='ADT',
            field=models.CharField(max_length=20, unique=True, verbose_name='ΑΔΤ'),
        ),
        migrations.AlterField(
            model_name='members',
            name='AFM',
            field=models.CharField(max_length=20, unique=True, verbose_name='ΑΦΜ'),
        ),
        migrations.AlterField(
            model_name='members',
            name='AMA',
            field=models.CharField(max_length=20, unique=True, verbose_name='ΑΜΑ'),
        ),
        migrations.AlterField(
            model_name='members',
            name='AMKA',
            field=models.CharField(max_length=20, unique=True, verbose_name='ΑΜΚΑ'),
        ),
        migrations.AlterField(
            model_name='members',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Διεύθυνση'),
        ),
        migrations.AlterField(
            model_name='members',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.banks', verbose_name='Τράπεζα'),
        ),
        migrations.AlterField(
            model_name='members',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Ημ. Γέννησης'),
        ),
        migrations.AlterField(
            model_name='members',
            name='date_of_deregistration',
            field=models.DateField(blank=True, null=True, verbose_name='Ημ. Λήξης'),
        ),
        migrations.AlterField(
            model_name='members',
            name='date_of_registration',
            field=models.DateField(blank=True, null=True, verbose_name='Ημ. Εγγραφής'),
        ),
        migrations.AlterField(
            model_name='members',
            name='driver_A',
            field=models.BooleanField(default=False, verbose_name='Δίπλωμα Α'),
        ),
        migrations.AlterField(
            model_name='members',
            name='driver_B',
            field=models.BooleanField(default=False, verbose_name='Δίπλωμα Β'),
        ),
        migrations.AlterField(
            model_name='members',
            name='driver_C',
            field=models.BooleanField(default=False, verbose_name='Δίπλωμα Γ'),
        ),
        migrations.AlterField(
            model_name='members',
            name='driver_D',
            field=models.BooleanField(default=False, verbose_name='Δίπλωμα Δ'),
        ),
        migrations.AlterField(
            model_name='members',
            name='fathers_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Πατρώνυμο'),
        ),
        migrations.AlterField(
            model_name='members',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Όνομα'),
        ),
        migrations.AlterField(
            model_name='members',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Επίθετο'),
        ),
        migrations.AlterField(
            model_name='members',
            name='lifter',
            field=models.BooleanField(default=False, verbose_name='Χειριστής Ανυψωτικού'),
        ),
        migrations.AlterField(
            model_name='members',
            name='mitroo_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Αριθμός Μητρώου'),
        ),
        migrations.AlterField(
            model_name='members',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.nationalities', verbose_name='Ιθαγένεια'),
        ),
        migrations.AlterField(
            model_name='members',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Παρατηρήσεις'),
        ),
        migrations.AlterField(
            model_name='members',
            name='omadiko',
            field=models.BooleanField(default=False, verbose_name='Ομαδικό'),
        ),
        migrations.AlterField(
            model_name='members',
            name='omadiko_exartomena',
            field=models.BooleanField(default=False, verbose_name='Ομαδικό Εξαρτώμενων'),
        ),
        migrations.AlterField(
            model_name='members',
            name='omadiko_from',
            field=models.DateField(blank=True, null=True, verbose_name='Ομαδικό Από'),
        ),
        migrations.AlterField(
            model_name='members',
            name='omadiko_to',
            field=models.DateField(blank=True, null=True, verbose_name='Ομαδικό Έως'),
        ),
        migrations.AlterField(
            model_name='members',
            name='pending_issues',
            field=models.TextField(blank=True, null=True, verbose_name='Εκκρεμότητες'),
        ),
        migrations.AlterField(
            model_name='members',
            name='phone_number1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Τηλ. 1'),
        ),
        migrations.AlterField(
            model_name='members',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Τηλ. 2'),
        ),
        migrations.AlterField(
            model_name='members',
            name='tk',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ΤΚ'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='date',
            field=models.DateField(verbose_name='Ημερομηνία'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='protocols/%Y/', verbose_name='Αρχείο'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='protocol_number',
            field=models.PositiveIntegerField(verbose_name='Αριθμός Πρωτοκόλλου'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='receiver_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Διεύθυνση Παραλήπτη'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='receiver_department',
            field=models.CharField(blank=True, max_length=200, verbose_name='Τμήμα Παραλήπτη'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='receiver_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Παραλήπτη'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='receiver_first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Όνομα Παραλήπτη'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='receiver_last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Επώνυμο Παραλήπτη'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='receiver_organization',
            field=models.CharField(blank=True, max_length=200, verbose_name='Οργανισμός Παραλήπτη'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='receiver_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Τηλέφωνο Παραλήπτη'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='receiver_tk',
            field=models.CharField(blank=True, max_length=10, verbose_name='Τ.Κ. Παραλήπτη'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='sender_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Διεύθυνση Αποστολέα'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='sender_department',
            field=models.CharField(blank=True, max_length=200, verbose_name='Τμήμα Αποστολέα'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='sender_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Αποστολέα'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='sender_first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Όνομα Αποστολέα'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='sender_last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Επώνυμο Αποστολέα'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='sender_organization',
            field=models.CharField(blank=True, max_length=200, verbose_name='Οργανισμός Αποστολέα'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='sender_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Τηλέφωνο Αποστολέα'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='sender_tk',
            field=models.CharField(blank=True, max_length=10, verbose_name='Τ.Κ. Αποστολέα'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='subject',
            field=models.CharField(max_length=500, verbose_name='Θέμα'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Έτος'),
        ),
    ]
