# Generated by Django 6.0.3 on 2026-04-05 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_banks_options_alter_companies_options_and_more'),
        ('core', '0016_alter_filefields_use_unique_upload_paths'),
    ]

    operations = [
    ]
