# Generated by Django 6.0.3 on 2026-04-05 15:10

import core.upload_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_merge_20260405_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Όνομα')),
                ('file_code', models.CharField(blank=True, max_length=100, verbose_name='Κωδικός Αρχείου')),
                ('file_type', models.CharField(max_length=100, verbose_name='Τύπος Αρχείου')),
                ('file', models.FileField(upload_to=core.upload_utils.UniqueUploadTo('documents/%Y/'), verbose_name='Αρχείο')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Έγγραφο',
                'verbose_name_plural': 'Έγγραφα',
                'ordering': ['name'],
            },
        ),
    ]
