# Generated by Django 6.0.3 on 2026-04-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_documentarchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentarchive',
            name='file_type',
            field=models.CharField(
                choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('word', 'Word')],
                max_length=20,
                verbose_name='Τύπος Αρχείου',
            ),
        ),
    ]
