# Generated by Django 6.0.3 on 2026-04-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_documentarchive_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='protocol_type',
            field=models.CharField(
                choices=[('incoming', 'Εισερχόμενο'), ('outgoing', 'Εξερχόμενο')],
                default='incoming',
                max_length=20,
                verbose_name='Τύπος Πρωτοκόλλου',
            ),
        ),
    ]
