# Generated by Django 6.0.3 on 2026-04-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_protocol_protocol_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='member_role',
            field=models.CharField(blank=True, choices=[('president', 'ΠΡΟΕΔΡΟΣ'), ('vice_president', 'ΑΝΤΙΠΡΟΕΔΡΟΣ'), ('general_secretary', 'ΓΕΝΙΚΟΣ ΓΡΑΜΜΑΤΕΑΣ'), ('deputy_general_secretary', 'ΑΝ. ΓΕΝ. ΓΡΑΜΜΑΤΕΑΣ'), ('treasurer', 'ΤΑΜΙΑΣ'), ('deputy_treasurer', 'ΑΝ. ΤΑΜΙΑΣ'), ('board_member', 'ΜΕΛΟΣ Δ.Σ.'), ('advisor', 'ΣΥΜΒΟΥΛΟΣ'), ('supervisor', 'ΕΦΟΡΟΣ'), ('member', 'ΜΕΛΟΣ')], max_length=40, null=True, verbose_name='Ιδιότητα'),
        ),
        migrations.AlterField(
            model_name='members',
            name='AFM',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ΑΦΜ'),
        ),
        migrations.AlterField(
            model_name='members',
            name='AMA',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ΑΜΑ'),
        ),
        migrations.AlterField(
            model_name='members',
            name='AMKA',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ΑΜΚΑ'),
        ),
        migrations.AlterField(
            model_name='members',
            name='member_registry_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Αριθμός Βιβλίου Μητρώου Μελών'),
        ),
    ]
